services:
  database:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: usuariosdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d usuariosdb" ]
      interval: 10s
      timeout: 5s
      retries: 6
  
  user-service:
    build: ./servicio-usuario
    container_name: user-service
    restart: unless-stopped
    environment:
      # Rutas internas dentro del contenedor donde montamos las llaves
      - PUBLIC_KEY_PATH=/app/keys/public-key.pem
      - PRIVATE_KEY_PATH=/app/keys/private-key.pem      # URL del data-service para comunicación entre microservicios
      - DATA_SERVICE_URL=http://data-service:8082/api/users
      - AUTH_SERVICE_URL=http://data-service:8082/api/auth
    volumes:
      - ./keys:/app/keys:ro
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - data-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 6

  data-service:
    build: ./servicio-datos
    container_name: data-service
    restart: unless-stopped
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: admin_user
      DB_PASSWORD: supersecurepassword
      DB_NAME: usuariosdb
    depends_on:
      - database
    ports:
      - "8082:8082"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 6

  otp-service:
    build: ./servicio-otp
    container_name: otp-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    networks:
      - app-network
    depends_on:
      - database
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/health" ]
      interval: 10s
      timeout: 5s
      retries: 6

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: